### ISSUE TITLE
Remove WinSock conversion utilities after they got merged in windows-rs

### ISSUE THREAD

**Issue by GamePad64** [GamePad64/tunio#18]
Related: https://github.com/microsoft/windows-rs/pull/1742

**Comment by ryancerium** [comment]
Where are the conversion utilities in this repo, as a point of comparison.

**Comment by GamePad64** [comment]
They are actually here: https://github.com/GamePad64/netconfig/blob/main/src/sys/win32/win_convert.rs
They are not in the same repo, but these crates are being developed together.

**Comment by ryancerium** [comment]
It's late here so I could be wrong, but I think your implementation isn't converting the port numbers from host byte order into network byte order, big-endian, in the Win32 structures.

**Comment by GamePad64** [comment]
Thanks for pointing it out! My implementation is definitely wrong. I don't use port numbers in my code, so I had no opportunity to test it in real life. I plan to remove most of it anyway :)
